---
title: Churn model
author: Lucas Bagge
date: '2020-07-09'
slug: churn-model
categories:
  - tidymodels
  - churn
  - plotly
tags:
  - tidymodels
  - churn
  - plotly
summary: 'I denne post vil jeg lave en churn model og se på tidymodels framwork til at vælge forskellige modeller.'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, warning = FALSE, message = FALSE, 
                      echo = TRUE, dpi = 300, cache.lazy = FALSE,
                      tidy = "styler", fig.width = 3, fig.height = 4)


# Modelling AlgorithmsS
library(glmnet) # Glmnet regression
library(ranger) # Random Forests

# Formating, Visualisations and tables
library(scales) # Number formats
library(knitr) # Table
library(gridExtra) # multiplot
library(e1071) # Summary distribution
library(skimr) # Summarise dataframe
library(corrplot) # Correlation plot
library(probably) # Probability thresholds
library(tidymodels)
library(caret)
# Data handling Packages
library(tidyverse) # Data handling/ Graphics
library(data.table) # Data handling
library(plotly)
```


# Introduktion

Det primære formål ved denne post er at undersøge `tidymodels` prediktive model framwork.
Max Kuhn skaberen af `caret` har erstattet den med tidymodels og er nu den store models
pakke, som bruges rund om i verden. For at undersøge workflow og underkomponenterne
vil jeg lave en churn model over et data sæt jeg har stødt på hos **Kaggle**.

Det specielle workflow fra tidymodels bygger på nogle nøgle pakker:

* `rsample` - Forskellige typer af resamples
* `recipes` - Transformation af modellens pre processiong 
* `parnip` - Et interface for model skabelse
* `tune` - Tune hyperparameter
* `dials` - Specifik hyperparameter tuning funktion
* `yardstick` - Måling af modellens præsentation

Ud over hele tidymodels framworked vil jeg og forsøge mig med at lave interaktive plots, ved hjælpm af `plotly`. 

